/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-10-15 06:02:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.9.RELEASE.jar", Long.valueOf(1631646404201L));
    _jspx_dependants.put("jar:file:/C:/Users/Nur/Desktop/SpringMVC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc_search/WEB-INF/lib/spring-webmvc-5.2.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1600138332000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform1_005ferrors_0026_005fpath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform1_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform1_005ferrors_0026_005fpath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <title>register</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body style=\"background:#e2e2e2\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container mt-4\">\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"col-md-8 mx-auto mb-3\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card p-4\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("						<h3 class=\"text-center\">Registration Form</h3>\r\n");
      out.write("						\r\n");
      out.write("						<div style=\"color:red; font-size:small;\">							\r\n");
      out.write("							");
      //  form1:errors
      org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form1_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform1_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
      boolean _jspx_th_form1_005ferrors_005f0_reused = false;
      try {
        _jspx_th_form1_005ferrors_005f0.setPageContext(_jspx_page_context);
        _jspx_th_form1_005ferrors_005f0.setParent(null);
        // /WEB-INF/views/form.jsp(31,7) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form1_005ferrors_005f0.setPath("student.*");
        int[] _jspx_push_body_count_form1_005ferrors_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_form1_005ferrors_005f0 = _jspx_th_form1_005ferrors_005f0.doStartTag();
          if (_jspx_th_form1_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_form1_005ferrors_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_form1_005ferrors_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_form1_005ferrors_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fform1_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form1_005ferrors_005f0);
        _jspx_th_form1_005ferrors_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form1_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_form1_005ferrors_005f0_reused);
      }
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<form action=\"processform\" method= \"post\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group mb-3\">\r\n");
      out.write("								<label for=\"name\" class=\"form-label\">Name</label> \r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"your name\" name=\"name\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"row mb-4\">\r\n");
      out.write("							\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("								\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"email\" class=\"form-label\">Email</label> \r\n");
      out.write("										<input type=\"email\" class=\"form-control\" placeholder=\"your email id\" name=\"email\">\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"col-md-6\">					\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"form-group\">\r\n");
      out.write("										<label for=\"dob\" class=\"form-label\">DOB</label> \r\n");
      out.write("										<input type=\"text\" class=\"form-control\" placeholder=\"dd/mm/yyyy\" name=\"dob\">\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("							\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card mb-3\">							\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"col-7\">\r\n");
      out.write("											<label for=\"inputAddress\" class=\"form-label\">Address</label>\r\n");
      out.write("											<input type=\"text\" name=\"address.street\" class=\"form-control\" placeholder=\"street, locality,\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-5\">\r\n");
      out.write("											<label for=\"inputCity\" class=\"form-label\">City</label> \r\n");
      out.write("											<input type=\"text\" name=\"address.city\" class=\"form-control\" placeholder=\"City\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-7\">\r\n");
      out.write("											<label for=\"inputState\" class=\"form-label\">State</label> \r\n");
      out.write("											<select class=\"form-select\" name=\"address.state\">\r\n");
      out.write("												<option selected>select state</option>\r\n");
      out.write("												<option>Assam</option>\r\n");
      out.write("												<option>NorthEast</option>\r\n");
      out.write("												<option>Maharastra</option>\r\n");
      out.write("												<option>Delhi</option>\r\n");
      out.write("												<option>Other</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-md-5\">\r\n");
      out.write("											<label for=\"inputZip\" class=\"form-label\">Pin</label> \r\n");
      out.write("											<input type=\"number\" name=\"address.pin\" class=\"form-control\" placeholder=\"Zip code\">\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group mb-3\">\r\n");
      out.write("								<label for=\"courses\" class=\"form-label\">Select Courses</label> <br>\r\n");
      out.write("									<div class=\"form-check\"><input class=\"form-check-input\" type=\"checkbox\" value=\"python\" name=\"courses\"> Python</div>\r\n");
      out.write("									<div class=\"form-check\"><input class=\"form-check-input\" type=\"checkbox\" value=\"java\" name=\"courses\">Java </div>\r\n");
      out.write("									<div class=\"form-check\"><input class=\"form-check-input\" type=\"checkbox\" value=\"android\" name=\"courses\">Android </div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group mb-3\">\r\n");
      out.write("								<label for=\"gender\" class=\"form-label\">Gender</label><br>\r\n");
      out.write("								<div class=\"form-check form-check-inline\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Male\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"gender\">Male</label>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"form-check form-check-inline\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Female\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"gender\">Female</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"form-check form-check-inline\">\r\n");
      out.write("									<input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Other\">\r\n");
      out.write("									<label class=\"form-check-label\" for=\"gender\">Others</label>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"mb-4\">				\r\n");
      out.write("								<label class=\"form-label\">Select Student Type</label>\r\n");
      out.write("								<select class=\"form-select\" name=\"stype\" required>\r\n");
      out.write("									<option selected value=\"\">choose..</option>\r\n");
      out.write("									<option value=\"new student\">New Student</option>\r\n");
      out.write("									<option value=\"old student\">Old Student</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"text-center mb-3\">\r\n");
      out.write("								<input type=\"submit\" value=\"SUBMIT\" class=\"btn btn-primary\">							\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\" integrity=\"sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js\" integrity=\"sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
